// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('PaktorApp', ['ui.router', 'ngAnimate', 'ui.bootstrap', 'debug']).controller('SomeCtrl', function($timeout) {});

}).call(this);

//# sourceMappingURL=app.js.map
